### ISSUE TITLE
Errors in console output after upgrading to 1.3.8

### ISSUE THREAD

**Issue by sethladd** [guillermooo/dart-sublime-bundle#502]
Errors in output:

```
unknown include #regex.dart
reloading plugin Default.block
reloading plugin Default.comment
reloading plugin Default.copy_path
reloading plugin Default.delete_word
reloading plugin Default.detect_indentation
reloading plugin Default.duplicate_line
reloading plugin Default.echo
reloading plugin Default.exec
reloading plugin Default.fold
reloading plugin Default.font
reloading plugin Default.goto_line
reloading plugin Default.history_list
reloading plugin Default.indentation
reloading plugin Default.kill_ring
reloading plugin Default.mark
reloading plugin Default.new_templates
reloading plugin Default.open_context_url
reloading plugin Default.open_file_settings
reloading plugin Default.open_in_browser
reloading plugin Default.pane
reloading plugin Default.paragraph
reloading plugin Default.paste_from_history
reloading plugin Default.quick_panel
reloading plugin Default.save_on_focus_lost
reloading plugin Default.scroll
reloading plugin Default.set_unsaved_view_name
reloading plugin Default.side_bar
reloading plugin Default.sort
reloading plugin Default.swap_line
reloading plugin Default.switch_file
reloading plugin Default.symbol
reloading plugin Default.transform
reloading plugin Default.transpose
reloading plugin Default.trim_trailing_white_space
reloading plugin CSS.css_completions
reloading plugin Diff.diff
reloading plugin HTML.encode_html_entities
reloading plugin HTML.html_completions
reloading plugin 0_package_control_loader.00-package_control
reloading plugin 0_package_control_loader.02-bz2
reloading plugin Package Control.bootstrap
reloading plugin Package Control.Package Control
reloading plugin Dart.AAA
reloading plugin Dart.analyzer
reloading plugin Dart.browser
reloading plugin Dart.cmds_search
reloading plugin Dart.comment
reloading plugin Dart.config_check
reloading plugin Dart.dartlint
Dartlint plugin loaded.
reloading plugin Dart.dev_cmds
reloading plugin Dart.docgen
reloading plugin Dart.edit
reloading plugin Dart.execute
reloading plugin Dart.format
reloading plugin Dart.misc
reloading plugin Dart.polymer
reloading plugin Dart.pub_support
reloading plugin Dart.run
reloading plugin Dart.stagehand
plugins loaded
Dart: Analyzer started.
Dart: Analysis Server version: 1.6.0
Package Control: Installing 1 upgrades
ignored packages updated to: ["Vintage", "Dart"]
unloading plugin Dart.AAA
unloading plugin Dart.analyzer
unloading plugin Dart.browser
unloading plugin Dart.cmds_search
unloading plugin Dart.comment
unloading plugin Dart.config_check
unloading plugin Dart.dartlint
unloading plugin Dart.dev_cmds
unloading plugin Dart.docgen
unloading plugin Dart.edit
unloading plugin Dart.execute
unloading plugin Dart.format
unloading plugin Dart.misc
unloading plugin Dart.polymer
unloading plugin Dart.pub_support
unloading plugin Dart.run
unloading plugin Dart.stagehand
reloading Packages/Dart/Support/Dart - Plugin Settings.sublime-settings
generating syntax summary
generating meta info summary
reloading Packages/User/Package Control.sublime-settings
reloading Packages/User/Preferences.sublime-settings
Package Control: Upgraded Dart to v1.3.8
Traceback (most recent call last):
  File "/Users/sethladd/Library/Application Support/Sublime Text 3/Packages/Dart/sublime_plugin_lib/sublime.py", line 20, in <lambda>
    sublime.set_timeout(lambda: f(*args, **kwargs), timeout)
  File "/Users/sethladd/Library/Application Support/Sublime Text 3/Packages/Dart/lib/analyzer/actions.py", line 45, in show_errors
    # todo (pp): notifications don't have id; process all
  File "./posixpath.py", line 394, in realpath
TypeError: 'NoneType' object is not subscriptable
Traceback (most recent call last):
  File "/Users/sethladd/Library/Application Support/Sublime Text 3/Packages/Dart/sublime_plugin_lib/sublime.py", line 20, in <lambda>
    sublime.set_timeout(lambda: f(*args, **kwargs), timeout)
  File "/Users/sethladd/Library/Application Support/Sublime Text 3/Packages/Dart/lib/analyzer/actions.py", line 45, in show_errors
    # todo (pp): notifications don't have id; process all
  File "./posixpath.py", line 394, in realpath
TypeError: 'NoneType' object is not subscriptable
Traceback (most recent call last):
  File "/Users/sethladd/Library/Application Support/Sublime Text 3/Packages/Dart/sublime_plugin_lib/sublime.py", line 20, in <lambda>
    sublime.set_timeout(lambda: f(*args, **kwargs), timeout)
  File "/Users/sethladd/Library/Application Support/Sublime Text 3/Packages/Dart/lib/analyzer/actions.py", line 45, in show_errors
    # todo (pp): notifications don't have id; process all
  File "./posixpath.py", line 394, in realpath
TypeError: 'NoneType' object is not subscriptable
ignored packages updated to: ["Vintage"]
reloading plugin Dart.AAA
reloading plugin Dart.analyzer
reloading plugin Dart.browser
reloading plugin Dart.cmds_search
reloading plugin Dart.comment
reloading plugin Dart.config_check
reloading plugin Dart.dartlint
Dartlint plugin loaded.
reloading plugin Dart.dev_cmds
reloading plugin Dart.docgen
reloading plugin Dart.edit
reloading plugin Dart.execute
reloading plugin Dart.format
reloading plugin Dart.misc
reloading plugin Dart.polymer
reloading plugin Dart.pub_support
reloading plugin Dart.run
reloading plugin Dart.stagehand
generating syntax summary
reloading Packages/Dart/Support/Dart - Plugin Settings.sublime-settings
generating meta info summary
Exception in thread RequestHandler-thread:
Traceback (most recent call last):
  File "/Users/sethladd/Library/Application Support/Sublime Text 3/Packages/Dart/analyzer.py", line 548, in run
    self.server.ready_barrier.wait()
  File "/Users/sethladd/Library/Application Support/Sublime Text 3/Packages/Dart/lib/analyzer/queue.py", line 81, in get
    prio, data = super().get(block, timeout)
  File "./queue.py", line 175, in get
queue.Empty

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./threading.py", line 901, in _bootstrap_inner
  File "/Users/sethladd/Library/Application Support/Sublime Text 3/Packages/Dart/analyzer.py", line 556, in run
AttributeError: 'NoneType' object has no attribute 'Empty'

reloading Packages/User/Package Control.sublime-settings
reloading Packages/User/Preferences.sublime-settings
unknown include #regex.dart
reloading Packages/User/Preferences.sublime-settings
```

**Comment by sethladd** [comment]
Here's the code I was looking at:

```
import 'package:sky/framework/fn.dart';

class HelloWorldApp extends App {
  @override
  UINode build() {
    return new Text('Hello, world!');
  }
}
```

also in that directory:

```
<sky>
<script>
import 'app.dart';

void main() {
  new HelloWorldApp();
}
</script>
</sky>
```

and

```
name: skyapp
dependencies:
 sky: any
```

**Comment by guillermooo** [comment]
Thanks! Is the plugin completely broken (i. e., no squiggly lines for errors, etc.)?

**Comment by guillermooo** [comment]
BTW, was this before restarting ST? Restarting is required.

**Comment by sethladd** [comment]
This was after a restart. I will double check after a clean restart.

**Comment by btwael** [comment]
Hello,
I remarked that this error happen (autocompletion & dartanalyser fails) when:

1. pubspec.yaml exists in working dir, and
2. packages directory doesn't exist

I fixed that by replacing in plugin 'Dart/lib/dart_project.py'
```py
...
class DartProject(object):
...
    def _get_top_level_dir(self, name):
        p = os.path.join(self.pubspec.parent, name)
        if os.path.exists(p):
            return p
```
with 
```py
...
class DartProject(object):
...
    def _get_top_level_dir(self, name):
        p = os.path.join(self.pubspec.parent, name)
        return p
```
