### ISSUE TITLE
g_server not being initialized

### ISSUE THREAD

**Issue by Ristovski** [guillermooo/dart-sublime-bundle#583]
On the latest ST3 dev build, this plugin seems completely broken.
Immediately upon loading it, the following error appears in the console:

```
Traceback (most recent call last):
  File "/home/rafael/.config/sublime-text-3/Packages/Dart/lib/path.py", line 78, in inner
    return func(self, view)
  File "/home/rafael/.config/sublime-text-3/Packages/Dart/analyzer.py", line 133, in on_activated
    g_server.add_root(view, view.file_name())
AttributeError: 'NoneType' object has no attribute 'add_root'
```

With many consecutive errors of similar nature (_`g_server` being `'NoneType'`_)

The dart SDK path is correct and the `dart_enable_analysis_server` setting has no effect on this issue.

I have confirmed my SDK install as working with both Atom and VSCode - where the plugins have no issue using it.

This plugin has not been updated since 2015 - shall it be considered no longer maintained?

**Comment by arthurlt** [comment]
Also wondering if this plugin is no longer being maintained?
